---
- name: setup my user
	ansible.builtin.command: chroot /mnt/gentoo bash -c 'source /etc/profile; useradd -m -G users,wheel,audio -s /bin/bash sdobrau'
- name: remove stage3 files
	ansible.builtin.file:
		src: /mnt/gentoo/stage3*
		state: absent
- name: done
	ansible.builtin.debug:
  msg: "Done configuring. Setup user and root passwords"
	
