
# normalization from reddit
# https://old.reddit.com/r/mpv/comments/1et0otc/audio_normalization_in_mpv/
2 af toggle "lavfi=[dynaudnorm=g=3:f=250:r=0.9:p=0.9:m=10]"

Ctrl+f seek  5
Ctrl+b seek -5
n seek 0.4
p seek -0.4
. frame-step                           # advance one frame and pause
, frame-back-step                      # go back by one frame and pa

[ multiply speed 1/1.1                 # decrease the playback speed
] multiply speed 1.1                   # increase the playback speed
KP8 multiply speed 1.3
KP4 seek -5
KP6 seek 5
KP2 multiply speed 0.9
KP5 ab-loop
{ multiply speed 0.5                   # halve the playback speed
} multiply speed 2.0                   # double the playback speed
BS set speed 1.0                       # reset the speed to normal

q quit
Ctrl+u-Ctrl+x-Ctrl+x quit-watch-later

SPACE cycle pause                          # toggle pause/playback mode

ENTER playlist-next                    # skip to the next file
P show-progress                        # show playback progress
` script-binding console/enable        # open the console

#z add sub-delay -0.1                   # shift subtitles 100 ms earlier
#Z add sub-delay +0.1                   # delay subtitles by 100 ms
#x add sub-delay +0.1                   # delay subtitles by 100 ms

Ctrl+- add volume -2
Ctrl+= add volume 2
m cycle mute                           # toggle mute
Alt+0 set current-window-scale 0.5     # halve the window size
Alt+1 set current-window-scale 1.0     # reset the window size
Alt+2 set current-window-scale 2.0     # double the window size
v cycle sub-visibility                 # hide or show the subtitles

T cycle ontop                          # toggle placing the video on top of other windows
f cycle fullscreen                     # toggle fullscreen
Ctrl+N playlist-next                     # skip to the next file
Ctrl+P playlist-prev                     # skip to the previous file
Ctrl+x-Ctrl+c quit

l ab-loop                              # set/clear A-B loop points
L cycle-values loop-file "inf" "no"    # toggle infinite looping

#ctrl+c quit 4
o script-binding osc/visibility      # cycle OSC visibility between never, auto (mouse-move) and always
Ctrl+h cycle-values hwdec "auto" "no"  # toggle hardware decoding
#F8 show-text ${playlist}               # show the playlist
#F9 show-text ${track-list}             # show the list of video, audio and sub tracks

, script_message bookmarker-menu
. script_message bookmarker-quick-save
s script_message unseenplaylist activate message
Ctrl+s script_message unseenplaylist mark-seen message
# s script_message unseenplaylist search message
# s script_message unseenplaylist clean message
