---

- name: sync the clock using chronyd
	ansible.builtin.command:
	command: chronyd -q
- name: import release keys to check the files against
	ansible.bultin.command:
		command: gpg --import /usr/share/openpgp-keys/gentoo-release.asc
- name: fetch desktop-systemd files
	ansible.builtin.script:
		cmd: /files/for-build/get-and-verify-stage-script.sh
- name: get name of archive
	ansible.builtin.command: "ls *.tar.xz"
	register: newest_gentoo
- name: extract stage tarball inside /mnt/gentoo
	ansible.builtin.command:
		command: "tar xpvf {{ newest_gentoo }} --xattrs-include='*.*' --numeric-owner -C /mnt/gentoo "
		dest: /mnt/gentoo
 # we are doing it without ansible_facts as nproc is most accurate
- name: get number of processors (threads) (cores times threads)
	ansible.builtin.command:
		command: nproc
	register: cpunr
- name: dynamically configure make.conf
	ansible.builtin.template:
    src: templates/make.conf.j2
		dest: /mnt/gentoo/etc/portage/make.conf
