---
- name: create efi boot partition
	community.general.parted:
		device: /dev/nvme0n1p1
		number: 1
		state: present
		fs_type: vfat
		part_end: 1GiB
- name: format boot partition
	community.general.filesystem:
		fstype: vfat
		opts:
			- "-F 32"

- name: create swap partition
	community.general.parted:
		device: /dev/nvme0n1p2
		number: 2
		state: present
		fs_type: swap
		part_end: 16GiB
- name: swapon the partition
	community.general.filesystem:
		fstype: swap
		dev: /dev/nvme0n1p2
- name: enable swap
	ansible.builtin.command: "swapon /dev/nvme0n1p2"

- name: create root partition
	community.general.parted:
		device: /dev/nvme0n1p3
		number: 3
		state: present
		fs_type: ext4
		part_end: 2TiB
- name: format root partition
	community.general.filesystem:
		fstype: ext4
		device: /dev/nvme0n1p3

- name: create /mnt/gentoo path
	ansible.builtin.file:
		path: /mnt/gentoo
		owner: root
		group: root
		mode: 0777
- name: mount root partition in /mnt/gentoo
	ansible.posix.mount:
		src: /dev/nvme0n1p3
		path: /mnt/gentoo
