# darkelf-features-0.1::darkelf
# created for ::darkelf overlay.
# by Simon the Sorcerer - http://homepages.uni-paderborn.de/neuron/gentoo/darkelf/
#
# This enables cleaning the distfiles after every emerge,
# to enable this feature set
# DARKELF_FEATURES="postmerge_distclean"
# in /etc/portage/make.conf or per command basis e.g.:
# DARKELF_FEATURES="postmerge_distclean" emerge ...
darkelf_postmerge_distclean() {
    echo cleaning distfiles for ${CATEGORY}/${PF} ...

    if [ -z $DISTDIR ] ; then
        echo ERROR: DISTDIR is empty!
        exit 1
    fi

    for f in $DISTDIR/* ; do
        echo deleting "`readlink -f $f`" ...
        rm -r "`readlink -f $f`"
    done
}


## requires iwdevtools app-portage-iwdevtools

post_pkg_preinst() {
    qa-cmp_post_pkg_preinst
		qa-openrc_post_pkg_preinst
}

post_pkg_postinst() {
    qa-vdb_post_pkg_postinst
    if grep -q "postmerge_distclean" <<< $DARKELF_FEATURES ; then
        darkelf_postmerge_distclean
    fi

}
