---
- name: copy over DNS info
	ansible.builtin.copy:
		remote_src: /etc/resolv.conf
		dest: /mnt/gentoo/etc/resolv.conf
- name: prepare mounts for chroot environment
	ansible.posix.mount:
		path: " {{ item.path }}"
		src: "{{ item.src }}"
		state: mounted
	with_items:
				- { path: '/mnt/gentoo/dev', src: '/dev' }
				- { path: '/mnt/gentoo/proc', src: '/proc' }
				- { path: '/mnt/gentoo/run', src: '/run' }
				- { path: '/mnt/gentoo/sys', src: '/sys' }
- name: mount EFI in /efi
	ansible.builtin.command: chroot /mnt/gentoo bash -c 'source /etc/profile; mount /dev/nvme0n1p1 /efi'
- name: sync ebuild repository
	ansible.builtin.command: chroot /mnt/gentoo bash -c 'source /etc/profile; emerge-webrsync'
- name: setup mirrors
	ansible.builtin.command: chroot /mnt/gentoo bash -c 'source /etc/profile; emerge --oneshot app-portage/mirrorselect && mirrorselect -i -o >> /etc/portage/make.conf'
- name: copy rsync mirrors
	ansible.builtin.command: chroot /mnt/gentoo bash -c 'source /etc/profile; mkdir /etc/portage/repos.conf && cp /usr/share/portage/config/repos.conf /etc/portage/repos.conf/gentoo.conf'
- name: update the repository again
  ansible.builtin.command: chroot /mnt/gentoo bash -c 'source /etc/profile; emerge --sync --quiet'
- name: set profile
	# [2]   default/linux/amd64/23.0/systemd (stable) *
	ansible.builtin.command: chroot /mnt/gentoo bash -c 'source /etc/profile; eslect profile set 2'
- name: generate cpuflags for all package's USE
	ansible.builtin.command: chroot /mnt/gentoo bash -c 'source /etc/profile; emerge --oneshot app-portage/cpuid2cpuflags && echo "*/* $(cpuid2cpuflags)" > /etc/portage/package.use/00cpu-flags'
- name: setup timezone in London
  ansible.builtin.command: chroot /mnt/gentoo bash -c 'source /etc/profile/; ln -sf /usr/share/zoneinfo/Europe/London /etc/localtime'
- name: set locale
	ansible.builtin.copy:
		src: files/for-build/locale.gen
		dest: /mnt/gentoo/etc/locale.gen
- name: generate and select locale
	# en_US.UTF-8
	ansible.builtin.command: chroot /mnt/gentoo bash -c 'source /etc/profile/; locale-gen && esleect locale set 3'
- name: license for linux firmware
	ansible.builtin.copy:
		src: files/for-build/kernel-package-license
		dest: /mnt/gentoo/etc/portage/package.license/kernel
